#include "vhci.h"

#include <wdmsec.h> // for IoCreateDeviceSecure

#include "device.h"
#include "usbip_vhci_api.h"

//
// This guid is used in IoCreateDeviceSecure call to create PDOs. The idea is to
// allow the administrators to control access to the child device, in case the
// device gets enumerated as a raw device - no function driver, by modifying the 
// registry. If a function driver is loaded for the device, the system will override
// the security descriptor specified in the call to IoCreateDeviceSecure with the 
// one specifyied for the setup class of the child device.
//
DEFINE_GUID(GUID_SD_USBIP_VHCI_PDO,
	0x9d3039dd, 0xcca5, 0x4b4d, 0xb3, 0x3d, 0xe2, 0xdd, 0xc8, 0xa8, 0xc5, 0x2e);
// {9D3039DD-CCA5-4b4d-B33D-E2DDC8A8C52E}

extern  void
bus_init_pdo(PDEVICE_OBJECT pdo, PFDO_DEVICE_DATA fdodata);

 NTSTATUS
bus_plugin_dev(ioctl_usbip_vhci_plugin *plugin, PFDO_DEVICE_DATA fdodata, PFILE_OBJECT fo)
{
	PDEVICE_OBJECT      pdo;
	PPDO_DEVICE_DATA    pdodata, old_pdodata;
	NTSTATUS            status;
	PLIST_ENTRY         entry;

	PAGED_CODE();

	DBGI(DBG_PNP, "Exposing PDO: addr: %d, vendor:product: %04x:%04x\n", plugin->addr, plugin->vendor, plugin->product);

	if (plugin->addr <= 0)
		return STATUS_INVALID_PARAMETER;

	ExAcquireFastMutex(&fdodata->Mutex);

	for (entry = fdodata->ListOfPDOs.Flink; entry != &fdodata->ListOfPDOs; entry = entry->Flink) {
		pdodata = CONTAINING_RECORD(entry, PDO_DEVICE_DATA, Link);
		if ((ULONG)plugin->addr == pdodata->SerialNo &&
			pdodata->common.DevicePnPState != SurpriseRemovePending) {
			ExReleaseFastMutex(&fdodata->Mutex);
			return STATUS_INVALID_PARAMETER;
		}
	}

	ExReleaseFastMutex(&fdodata->Mutex);

	// Create the PDO
	//
	DBGI(DBG_PNP, "fdodata->NextLowerDriver = 0x%p\n", fdodata->NextLowerDriver);

	//
	// PDO must have a name. You should let the system auto generate a
	// name by specifying FILE_AUTOGENERATED_DEVICE_NAME in the
	// DeviceCharacteristics parameter. Let us create a secure deviceobject,
	// in case the child gets installed as a raw device (RawDeviceOK), to prevent
	// an unpriviledged user accessing our device. This function is avaliable
	// in a static WDMSEC.LIB and can be used in Win2k, XP, and Server 2003
	// Just make sure that  the GUID specified here is not a setup class GUID.
	// If you specify a setup class guid, you must make sure that class is
	// installed before enumerating the PDO.
	//

	status = IoCreateDeviceSecure(fdodata->common.Self->DriverObject,
		sizeof(PDO_DEVICE_DATA),
		NULL,
		FILE_DEVICE_BUS_EXTENDER,
		FILE_AUTOGENERATED_DEVICE_NAME | FILE_DEVICE_SECURE_OPEN,
		FALSE,
		&SDDL_DEVOBJ_SYS_ALL_ADM_RWX_WORLD_RWX_RES_RWX, // allow normal users to access the devices
		(LPCGUID)&GUID_SD_USBIP_VHCI_PDO,
		&pdo);
	if (!NT_SUCCESS(status)) {
		return status;
	}

	pdodata = (PPDO_DEVICE_DATA)pdo->DeviceExtension;

	pdodata->vendor = plugin->vendor;
	pdodata->product = plugin->product;
	pdodata->revision = plugin->version;
	pdodata->usbclass = plugin->class;
	pdodata->subclass = plugin->subclass;
	pdodata->protocol = plugin->protocol;
	pdodata->inum = plugin->inum;

	old_pdodata = (PPDO_DEVICE_DATA)InterlockedCompareExchangePointer(&(fo->FsContext), pdodata, 0);
	if (old_pdodata) {
		DBGI(DBG_GENERAL, "you can't plugin again");
		IoDeleteDevice(pdo);
		return STATUS_INVALID_PARAMETER;
	}
	pdodata->SerialNo = plugin->addr;
	pdodata->fo = fo;
	pdodata->devid = plugin->devid;
	pdodata->speed = plugin->speed;
	bus_init_pdo(pdo, fdodata);

	//
	// Device Relation changes if a new pdo is created. So let
	// the PNP system now about that. This forces it to send bunch of pnp
	// queries and cause the function driver to be loaded.
	//
	IoInvalidateDeviceRelations(fdodata->UnderlyingPDO, BusRelations);

	return status;
}
